### ISSUE TITLE
How to change pips color?

### ISSUE THREAD

**Issue by biapar** [Mobius1/Pageable#17]
How to change pips color?

**Comment by Mobius1** [comment]
The `span` elements within the pips are the ones with the colour applied so you need to adjust the `background-color` property if you want a different colour:

```markup
<nav class="pg-pips">
  <ul>
    <li><a href="#page-1" class="active"><span></span></a></li>
    <li><a href="#page-2"><span></span></a></li>
    <li><a href="#page-3"><span></span></a></li>
    ...
  </ul>
</nav>
```

```css
.pg-pips span {
    background-color: COLOUR_CODE;
}
```
